// helper: image path from first name
const getImage = (firstName) => `/assets/team/${firstName.toLowerCase()}.jpg`;

export const teamMembers = [
  {
    name: "Lucy Lu",
    team: "WiCS",
    title: "youCode Co-lead",
    src: getImage("lucy"),
  },
  {
    name: "Amara Oriaku",
    team: "WiDS",
    title: "youCode Co-lead",
    src: getImage("amara"),
  },
  {
    name: "Aiko Sumarno",
    team: "WiCS",
    title: "youCode Sponsorship & Outreach Coordinator",
    src: getImage("aiko"),
  },
  {
    name: "Tiya Verma",
    team: "WiCS",
    title: "youCode Marketing and Engagement Coordinator",
    src: getImage("tiya"),
  },
  {
    name: "Anisa Pirani",
    team: "WiDS",
    title: "Events & Experience",
    src: getImage("anisa"),
  },
  {
    name: "Claire Zhang",
    team: "WiDS",
    title: "Logistics & Operations",
    src: getImage("claire"),
  },

  // WiCS
  {
    name: "Karan Chick",
    team: "WiCS",
    title: "President",
    src: getImage("karan"),
  },
  {
    name: "Selin Uz",
    team: "WiCS",
    title: "President",
    src: getImage("selin"),
  },

  {
    name: "Kimberly Tran",
    team: "WiCS",
    title: "VP External",
    src: getImage("kim"),
  },
  {
    name: "Ananyaa Chopra",
    team: "WiCS",
    title: "VP Community",
    src: getImage("ananyaa"),
  },
  {
    name: "Kashish Rohira",
    team: "WiCS",
    title: "VP Mentorship",
    src: getImage("kashish"),
  },
  {
    name: "Stellar Shar",
    team: "WiCS",
    title: "VP Communications",
    src: getImage("stellar"),
  },

  {
    name: "Ramona Karimi",
    team: "WiCS",
    title: "External Events Director",
    src: getImage("ramona"),
  },
  {
    name: "Liza Patel",
    team: "WiCS",
    title: "External Events Director",
    src: getImage("liza"),
  },
  {
    name: "Katja Radovic-Jonsson",
    team: "WiCS",
    title: "Community Events Director",
    src: getImage("katja"),
  },
  {
    name: "Amelie Tam",
    team: "WiCS",
    title: "Community Events Director",
    src: getImage("amelie"),
  },
  {
    name: "Sarah Liu",
    team: "WiCS",
    title: "Conference Lead",
    src: getImage("sarah"),
  },
  {
    name: "Pari Khanna",
    team: "WiCS",
    title: "Outreach Coordinator",
    src: getImage("pari"),
  },
  {
    name: "Giorgia Markos",
    team: "WiCS",
    title: "Social Media Coordinator",
    src: getImage("giorgia"),
  },
  {
    name: "Emily Hou",
    team: "WiCS",
    title: "Social Media Coordinator",
    src: getImage("emily"),
  },
  {
    name: "Maryum Chaudhry",
    team: "WiCS",
    title: "Graphic Designer",
    src: getImage("maryum"),
  },
  {
    name: "Grace Bouman",
    team: "WiCS",
    title: "Graphic Designer",
    src: getImage("grace"),
  },

  {
    name: "Anica Mok",
    team: "WiCS",
    title: "Webmaster",
    src: getImage("anica"),
  },
  {
    name: "Carissa Or",
    team: "WiCS",
    title: "Webmaster",
    src: getImage("carissa"),
  },
  {
    name: "Wendy Tso",
    team: "WiCS",
    title: "Newsletter Coordinator",
    src: getImage("wendy"),
  },
  {
    name: "Prajna Nayak",
    team: "WiCS",
    title: "Podcast Coordinator",
    src: getImage("prajna"),
  },
  {
    name: "Leticia Scudeller Carvalho",
    team: "WiCS",
    title: "Mentorship Coordinator",
    src: getImage("leticia"),
  },
  {
    name: "Jiayin Kralik",
    team: "WiCS",
    title: "Grad Mentorship Coordinator",
    src: getImage("jiayin"),
  },
  {
    name: "Vivian White",
    team: "WiCS",
    title: "Grad Mentorship Coordinator",
    src: getImage("vivian"),
  },
  {
    name: "Irmak Bayir",
    team: "WiCS",
    title: "Finance Director",
    src: getImage("irmak"),
  },
  {
    name: "Jaza Khan",
    team: "WiCS",
    title: "Internal Relations Coordinator",
    src: getImage("jaza"),
  },
  {
    name: "Ashley Lam",
    team: "WiCS",
    title: "First Year Representative",
    src: getImage("ashley"),
  },
  {
    name: "Jessica Tsai",
    team: "WiCS",
    title: "First Year Representative",
    src: getImage("jessica"),
  },

  //WiDS
{
  name: "Kaitlin Khu",
  team: "WiDS",
  title: "Co-President",
  src: getImage("kaitlin"),
},
{
  name: "Zelalem Araya",
  team: "WiDS",
  title: "Co-President",
  src: getImage("zelalem"),
},
{
  name: "Tumi Fabiyi",
  team: "WiDS",
  title: "VP External",
  src: getImage("tumi"),
},
{
  name: "Nicole Pan",
  team: "WiDS",
  title: "External Outreach Director",
  src: getImage("nicole"),
},
{
  name: "Gwynnie Guo",
  team: "WiDS",
  title: "External Outreach Director",
  src: getImage("gwynnie"),
},
{
  name: "Lilit Vanyan",
  team: "WiDS",
  title: "External Outreach Director",
  src: getImage("lilit"),
},
{
  name: "Salma Yazki",
  team: "WiDS",
  title: "VP Finance",
  src: getImage("salma"),
},
{
  name: "Rosie Kong",
  team: "WiDS",
  title: "First Year Representative",
  src: getImage("rosie"),
},
{
  name: "Kendra Robertson",
  team: "WiDS",
  title: "First Year Representative",
  src: getImage("kendra"),
},
{
  name: "Rachel Weng",
  team: "WiDS",
  title: "VP Internal",
  src: getImage("rachel"),
},
{
  name: "Jocelyn Kwa",
  team: "WiDS",
  title: "Internal Outreach Director",
  src: getImage("jocelyn"),
},
{
  name: "Megan Ong",
  team: "WiDS",
  title: "Internal Outreach Director",
  src: getImage("megan"),
},
{
  name: "Olivia Lam",
  team: "WiDS",
  title: "Co-VP Marketing",
  src: getImage("olivia"),
},
{
  name: "Eleny Xia",
  team: "WiDS",
  title: "Co-VP Marketing",
  src: getImage("eleny"),
},
{
  name: "Delia Zhang",
  team: "WiDS",
  title: "Marketing Design Director",
  src: getImage("delia"),
},
{
  name: "Ella Ilan",
  team: "WiDS",
  title: "Marketing Design Director",
  src: getImage("ella"),
},
{
  name: "Kayla Lin",
  team: "WiDS",
  title: "Social Media Director",
  src: getImage("kayla"),
},
{
  name: "Kelly Wei Jin",
  team: "WiDS",
  title: "Social Media Director",
  src: getImage("kelly"),
},
{
  name: "Amy Cao",
  team: "WiDS",
  title: "Dev Lead",
  src: getImage("amy"),
},
{
  name: "Krupa Raval",
  team: "WiDS",
  title: "Developer",
  src: getImage("krupa"),
},
{
  name: "Rachel Wang",
  team: "WiDS",
  title: "Developer",
  src: getImage("rachelwang"),
},
{
  name: "Cathy Le",
  team: "WiDS",
  title: "Developer",
  src: getImage("cathy"),
},
{
  name: "Yuko Yajima",
  team: "WiDS",
  title: "UX/UI Designer",
  src: getImage("yuko"),
},
{
  name: "Sabrina Lou",
  team: "WiDS",
  title: "VP Events",
  src: getImage("sabrina"),
},
{
  name: "Bhumika Kalra",
  team: "WiDS",
  title: "Events Director",
  src: getImage("bhumika"),
},
{
  name: "Dhweya Modi",
  team: "WiDS",
  title: "Events Director",
  src: getImage("dhweya"),
},
{
  name: "Nandini Rana",
  team: "WiDS",
  title: "Events Director",
  src: getImage("nandini"),
},
{
  name: "Neha Menon",
  team: "WiDS",
  title: "Events Director",
  src: getImage("neha"),
},
];
